# Generated by Django 5.0.6 on 2024-07-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arriendo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comuna",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="region",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
