# Generated by Django 5.0.6 on 2024-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arriendo_app", "0002_alter_comuna_nombre_alter_region_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipousuario",
            name="descripcion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
