# Generated by Django 5.0.6 on 2024-07-12 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arriendo_app", "0004_pais_alter_usuario_rut_region_pais"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="pais",
        ),
    ]
