# Generated by Django 5.0.6 on 2024-07-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arriendo_app", "0005_remove_region_pais"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="arriendo_app.pais",
            ),
        ),
    ]
