# Generated by Django 5.0.6 on 2024-07-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arriendo_app", "0006_region_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="direccion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Direccion",
        ),
    ]
